### PR TITLE
feat(chart): Added a volume with a toggle for each app 

### LINKED ISSUE #26: [FR] Having different PV for each tool
**Is your feature request related to a problem? Please describe.**
When using the current setup, all the tools are configured directly with the same persistent volume, where the media, configs and apparently sqlite databases are created. This causes issues for some storage backends that might not be well suited to run databases, such as NFS or SMB shares.

**Describe the solution you'd like**
I'd like to add a specific PV/PVC for each tool, in addition to the main "media" PV where all the movies and shows are stored.

**Describe alternatives you've considered**
There is already the additional PV field under `spec.general.storage.volumes` but this is not really helpful to set specific mounts on specific tools. 

**Additional context**
Jackett, transmission, plex and sabnzbd seem to work as they all just rely on flat files, while sonarr and radarr run sqlite instances and rely on those.

I'm opening this issue for the discussion, I'll bring the changes (or at least the way I see them) in a PR if we define a good retro-compatible way to do this.

### PR DESCRIPTION
**Pull request by InputObject2**
Fixes #26 

If the volumes are not specified, the default is to put everything on the current storage (where the media is). Each tool can create a persistentVolumeClaim if it's `volume` field is set.

For example to add a config volume for Sonarr:

```yaml
sonarr:
  enabled: true
  # < ... >
  volume:
    name: pvc-sonarr-config
    storageClassName: longhorn
    annotations:
      my-annotation/test: my-value
    labels:
      my-label/test: my-other-value
    accessModes: ReadWriteOnce
    storage: 5Gi
    selector: {}
```

### CODE REVIEW

**Comment by kubealex** [comment]
Look good to me, I'll run a couple of tests on it and rebuild the new version of the operator if everything is going as expected. Thanks a lot for the effort!

**Review by kubealex — CHANGES_REQUESTED** [review]
So far it looks good to me.
Some changes needed:
- Add a space in each README entries between the first column delimiter and the description
- Add dashes in the if/else/end statements to avoid blank lines in template rendering in *-resources.yml
- Same as before in storage-resources.yml file for those that are missing.

After you do this I will merge it and rebuild the operator :)

Thanks a lot!

**Comment by InputObject2** [comment]
Sorry for leaving the PR pending this long, I just sent it and completely forgot about it.

> Add a space in each README entries between the first column delimiter and the description

fixed

> Add dashes in the if/else/end statements to avoid blank lines in template rendering in *-resources.yml

fixed

> Same as before in storage-resources.yml file for those that are missing.

I rebased on dc5b9ac5ad282166bff1a2c41b007fc05dbd8b6e and I went through the file and we have all the same sections except the ones I added, but not in the same order? Did you use a linter or something to remake the file?

**Review by kubealex — APPROVED** [review]
LGTM

**Pull request merged**
