### PR TITLE
feat(prowlarr): #31 Added prowlarr and extra lb annotations

### LINKED ISSUE #31: Add support for prowlarr
[prowlarr](https://github.com/Prowlarr/Prowlarr) is a better alternative compared with jackett. https://hub.docker.com/r/linuxserver/prowlarr have already identical configuration container image.

### PR DESCRIPTION
**Pull request by InputObject2**
Fixes #31

### CODE REVIEW

**Comment by InputObject2** [comment]
Since 90% of the code is similar between all these tools, I think we should look into a way to abstract them into a common chart and just add the differences in.

**Review by kubealex — CHANGES_REQUESTED** [review]
LGTM overall, some changes needed:
- Document the extraLBService annotations in the README for each component
- Document the Prowlarr values in the readme
- Review the Prowlarr definition, some typos are present (referencing jackett, mostly)
- Edit the k8s-mediaserver.yml according to the new values.yaml (copy/paste + indent is enough)

**Comment by kubealex** [comment]
@InputObject2 I had to revert this one as integrations tests are failing on ingress wget, am I missing something? - #58

**Comment by 95gabor** [comment]
@kubealex Annotations are not working for me with ArgoCD and Helm chat in `v0.8.0` I had to revert to `v0.7.0`.

**Pull request merged**
